# Generated by Django 5.0.4 on 2024-04-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
    ]
