# Generated by Django 5.0.4 on 2024-04-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
    ]
